name: [release] Create PR on WebClient

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  create-pr:
    if: github.event.release.prerelease == false
    runs-on: ubuntu-latest

    steps:
    - name: Checkout webclient repository
      uses: actions/checkout@v2
      with:
        repository: 'gisce/webclient'
        ref: main
        token: ${{ secrets.GH_PAT }}

    - name: Update library version in package.json
      run: |
        NEW_VERSION=${{ github.event.release.tag_name }}
        NEW_VERSION=${NEW_VERSION#v}  # Remove the leading 'v'
        sed -i 's|"@gisce/react-ooui": "[^"]*"|"@gisce/react-ooui": "'"$NEW_VERSION"'"|' package.json

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.5.0'

    - name: Install npm dependencies and generate package-lock.json
      run: |
        npm install

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GH_PAT }}
        commit-message: "fix: Update @gisce/react-ooui to ${{ github.event.release.tag_name }}"
        title: "Update @gisce/react-ooui to ${{ github.event.release.tag_name }}"
        branch: "update-react-ooui-${{ github.event.release.tag_name }}"
