name: Release

on:
  push:
    branches:
      - v2
      - v2-develop
      - alpha
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.5.0'

      - name: Install semver globally (For v2-develop only)
        if: github.ref == 'refs/heads/v2-develop'
        run: npm install -g semver

      - name: Checkout v2 Branch (For v2-develop only)
        if: github.ref == 'refs/heads/v2-develop'
        uses: actions/checkout@v2
        with:
          ref: v2
          fetch-depth: 0

      - name: Get parent version (For v2-develop only)
        if: github.ref == 'refs/heads/v2-develop'
        id: get_parent_version
        run: |
          PARENT_VERSION=$(node -p "require('./package.json').version")
          echo "PARENT_VERSION=$PARENT_VERSION" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get child version and compare with parent version (For v2-develop only)
        if: github.ref == 'refs/heads/v2-develop'
        run: |
          CHILD_VERSION=$(node -p "require('./package.json').version")
          echo "CHILD_VERSION=$CHILD_VERSION" >> $GITHUB_ENV
          if [ $(semver $CHILD_VERSION $PARENT_VERSION -l) == "true" ]; then
            echo "CHILD_BEHIND_PARENT=true" >> $GITHUB_ENV
          else
            echo "CHILD_BEHIND_PARENT=false" >> $GITHUB_ENV

      - name: Update version if behind (For v2-develop only)
        if: github.ref == 'refs/heads/v2-develop' && env.CHILD_BEHIND_PARENT == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npm version ${{ env.PARENT_VERSION }} --no-git-tag-version
          git commit -am "Update version to ${{ env.PARENT_VERSION }}"
          git push

      - name: Install Dependencies
        run: npm ci

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: npx semantic-release