name: Reusable Workflow

on:
  workflow_call:
    inputs:
      release_type:
        description: 'The type of release (patch, minor, major)'
        required: true
        type: string
      tag_name:
        description: 'The tag name of the release'
        required: true
        type: string

jobs:
  process-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Process Release
        run: |
          echo "Release type: ${{ inputs.release_type }}"
          echo "Tag name: ${{ inputs.tag_name }}"
