name: Sync Alpha and Beta branches

env:
  REPO_NAME: "gisce/react-ooui"

on:
  push:
    branches:
      - v2

jobs:
  sync-branches:
    name: Create sync PRs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ['alpha', 'v2-develop']
    steps:
      - name: Call create sync pr
        uses: gisce/create-sync-pr@v0.0.2
        with:
          repository: ${{ env.REPO_NAME }}
          targetBranch: ${{ matrix.target }}
          baseBranch: v2
          githubToken: ${{ secrets.GH_PAT }}
          releaseType: none
